const ADD_IN_COMMON_LIST = 'ADD_IN_COMMON_LIST';
const DELETE_IN_COMMON_LIST = 'DELETE_IN_COMMON_LIST';
const TOGGLE_IN_COMMON_LIST = 'TOGGLE_IN_COMMON_LIST'; 

export { 
    ADD_IN_COMMON_LIST, 
    DELETE_IN_COMMON_LIST,
    TOGGLE_IN_COMMON_LIST 
};
